name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential g++
        
    - name: Compile and run tests
      run: |
        # Компилируем программу
        g++ -std=c++11 -o student_db main.cpp
        
        # Запускаем программу (тесты выполняются автоматически при старте)
        ./student_db <<< "0"
        
        # Проверяем код возврата
        if [ $? -eq 0 ]; then
          echo "Тесты прошли успешно"
        else
          echo "Тесты провалились"
          exit 1
        fi
